### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by nandorojo** [mwarger/expo-nextjs-dripsy-moti-setup#3]
Mind walking through the steps on the readme of what you did to set this up / get it working?

**Comment by mwarger** [comment]
quick notes

- use expo with next template (https://docs.expo.dev/guides/using-nextjs/#-setup)
- add ts file to force typescript config, follow instructions
- follow dripsy install instructions for nextjs (https://github.com/nandorojo/dripsy#for-ssr-apps-nextjs-gatsby-etc)
- follow moti installation instructions (https://moti.fyi/next#step-1)
  - see https://github.com/mwarger/expo-nextjs-dripsy-moti-setup/blob/main/next.config.js for the full config that's necessary
- update babel config (https://github.com/mwarger/expo-nextjs-dripsy-moti-setup/blob/main/babel.config.js) 
  - this was found after some help (see https://github.com/nandorojo/moti/issues/36#issuecomment-913962808 and following comments)

**Comment by mwarger** [comment]
Update the readme @nandorojo
